[package]
name = "EHTML"
version = "0.2.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1.10.3"
#html5ever = "0.26"
#markup5ever_rcdom = "0.2.0"
